from __future__ import annotations
from enum import Enum


class Zone(str, Enum):
    DEF_THIRD_LEFT = 'DEF_THIRD_LEFT'
    DEF_THIRD_CENTER = 'DEF_THIRD_CENTER'
    DEF_THIRD_RIGHT = 'DEF_THIRD_RIGHT'
    MID_THIRD_LEFT = 'MID_THIRD_LEFT'
    MID_THIRD_CENTER = 'MID_THIRD_CENTER'
    MID_THIRD_RIGHT = 'MID_THIRD_RIGHT'
    ATT_THIRD_LEFT = 'ATT_THIRD_LEFT'
    ATT_THIRD_CENTER = 'ATT_THIRD_CENTER'
    ATT_THIRD_RIGHT = 'ATT_THIRD_RIGHT'

