name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  run-sim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run simulation
        run: |
          python main.py --seed 42 --density high > match_log.txt
          echo "Simulation finished. Log saved to match_log.txt"

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: match-log
          path: match_log.txt
